# Generated by Django 4.1.3 on 2022-11-03 00:34
import datetime

from django.db import migrations


def populate_with_dummy_data(apps, schema_editor):
    Rental = apps.get_model('reserve_service_app', 'Rental')
    Reservation = apps.get_model('reserve_service_app', 'Reservation')
    
    r1 = Rental(name='Rental-1')
    r2 = Rental(name='Rental-2')
    
    r1.save()
    r2.save()
    
    res1 = Reservation(
        rental=r1,
        checkin=datetime.datetime(2022, 1, 1),
        checkout=datetime.datetime(2022, 1, 13)
    )
    res1.save()
    
    res2 = Reservation(
        rental=r1,
        checkin=datetime.datetime(2022, 1, 20),
        checkout=datetime.datetime(2022, 2, 10)
    )
    res2.save()
    
    res3 = Reservation(
        rental=r1,
        checkin=datetime.datetime(2022, 2, 20),
        checkout=datetime.datetime(2022, 3, 10)
    )
    res3.save()
    
    res4 = Reservation(
        rental=r2,
        checkin=datetime.datetime(2022, 1, 2),
        checkout=datetime.datetime(2022, 1, 20)
    )
    res4.save()
    
    res5 = Reservation(
        rental=r2,
        checkin=datetime.datetime(2022, 1, 20),
        checkout=datetime.datetime(2022, 2, 11)
    )
    res5.save()


class Migration(migrations.Migration):

    dependencies = [
        ('reserve_service_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_with_dummy_data)
    ]
