# Generated by Django 4.1.3 on 2022-11-03 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserve_service_app', '0002_auto_20221103_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='rental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reserve_service_app.rental'),
        ),
    ]
